CREATE TABLE CLIENT
(
	CLIENT_ID INT PRIMARY KEY IDENTITY(1,1),
	NUME VARCHAR(30),
	PRENUME VARCHAR(30),
	COD_CLIENT INT
)

CREATE TABLE OPERATOR
(
	OPERATOR_ID INT PRIMARY KEY IDENTITY(1,1),
	NUME VARCHAR(30),
	PRENUME VARCHAR(30),
	FUNCTIA VARCHAR(50),
	USERNAME VARCHAR(20),
	PASS VARCHAR(20),
	COD INT,
	TIP_ACCES INT
)

CREATE TABLE CEC
(
	CEC_ID INT PRIMARY KEY IDENTITY(1,1),
	OPERATOR_ID INT FOREIGN KEY REFERENCES OPERATOR(OPERATOR_ID),
	CLIENT_ID INT FOREIGN KEY REFERENCES CLIENT(CLIENT_ID),
	--FIRMA_ID INT FOREIGN KEY REFERENCES FIRMA(FIRMA_ID),
	NR_CEC INT,
	DATA_CEC DATE,
	SUMA_CEC DECIMAL(9,2)
)

CREATE TABLE SERVICII
(
	SERVICIU_ID INT PRIMARY KEY IDENTITY(1,1),
	DENUMIRE VARCHAR(100),
	PRET DECIMAL(9,1)
)

CREATE TABLE MATERIAL
(
	MATERIAL_ID INT PRIMARY KEY IDENTITY(1,1),
	DENUMIRE VARCHAR(100),
	PRET DECIMAL(9,2)
)

CREATE TABLE ARTICOL
(
	ARTICOL_ID INT PRIMARY KEY IDENTITY(1,1),
	DENUMIRE VARCHAR(100),
	PRET DECIMAL(9,2)
)

CREATE TABLE COMADA
(
	COMANDA_ID INT PRIMARY KEY IDENTITY(1,1),
	CLIENT_ID INT FOREIGN KEY REFERENCES CLIENT(CLIENT_ID),
	OPERATOR_ID INT FOREIGN KEY REFERENCES OPERATOR(OPERATOR_ID),
	SERVICIU1_ID INT FOREIGN KEY REFERENCES SERVICII(SERVICIU_ID),
	SERVICIU2_ID INT FOREIGN KEY REFERENCES SERVICII(SERVICIU_ID),
	SERVICIU3_ID INT FOREIGN KEY REFERENCES SERVICII(SERVICIU_ID),
	SERVICIU4_ID INT FOREIGN KEY REFERENCES SERVICII(SERVICIU_ID),
	SERVICIU5_ID INT FOREIGN KEY REFERENCES SERVICII(SERVICIU_ID),
	ARTICOL1_ID INT FOREIGN KEY REFERENCES ARTICOL(ARTICOL_ID),
	ARTICOL2_ID INT FOREIGN KEY REFERENCES ARTICOL(ARTICOL_ID),
	ARTICOL3_ID INT FOREIGN KEY REFERENCES ARTICOL(ARTICOL_ID),
	ARTICOL4_ID INT FOREIGN KEY REFERENCES ARTICOL(ARTICOL_ID),
	ARTICOL5_ID INT FOREIGN KEY REFERENCES ARTICOL(ARTICOL_ID),
	MATERIAL1_ID INT FOREIGN KEY REFERENCES MATERIAL(MATERIAL_ID),
	MATERIAL2_ID INT FOREIGN KEY REFERENCES MATERIAL(MATERIAL_ID),
	MATERIAL3_ID INT FOREIGN KEY REFERENCES MATERIAL(MATERIAL_ID),
	MATERIAL4_ID INT FOREIGN KEY REFERENCES MATERIAL(MATERIAL_ID),
	MATERIAL5_ID INT FOREIGN KEY REFERENCES MATERIAL(MATERIAL_ID),
	CEC_ID INT FOREIGN KEY REFERENCES CEC(CEC_ID),
	ACTIV BIT DEFAULT 1,
	SUMA_TOTAL DECIMAL(9,2)
)

--POPULAREA BAZEI DE DATE
INSERT INTO OPERATOR(NUME,PRENUME,FUNCTIA,USERNAME,PASS,COD,TIP_ACCES)
VALUES('VOICU','DUMITRU','CASIER','VOICU123','123',' ',NULL),
		('CENTROI','ALEXANDRU','CASIER','CENTROIA','123',' ',NULL), 
		('MARDARI','ANA','ADMINISTRATOR','MARDARI12','12345',' ',NULL),
		('ILONICI','VASILE','DEPOZITAR','ILONICI4','1234',' ',NULL),
		('FEDER','ANTON','ADMINISTRATOR','FEDER_A','12345',' ',NULL)

INSERT INTO CLIENT(NUME,PRENUME,COD_CLIENT)
VALUES('STEPAN','ALEXEI',123),
      ('IDEL','STEFAN',112)

INSERT INTO SERVICII(DENUMIRE,PRET)
VALUES('SPALAT',100),
		('CALCAT',50),
		('SCOS SCAME',30)

INSERT INTO MATERIAL(DENUMIRE,PRET)
VALUES('MATASE', 50),
		('ATLAS',5),
		('FATIN',20),
		('CASMIR',2),
		('LANA',10)
	
INSERT INTO ARTICOL(DENUMIRE,PRET)
	VALUES('PANTALONI',30),
			('TRICOU',20),
			('PERNA',50)

